### ISSUE TITLE
Adding a fastener messes up some settings (fixed by selecting preset in Object properties)

### ISSUE THREAD

**Issue by VanessaE** [faerietree/add_mesh_fastener#7]
When editing an existing bolt from the old builtin bolt library, of course all settings are invalid, however, the scale setting operates differently here.  I have to set it to 0.1 to get parts that are sized properly, while Mesh -> Add -> Bolt requires a scale setting of 1.0.

My overall blender scale for the model in question is 10.0 (which, when exported to STL, with its scale set to 1.0, produces life-size parts).

**Comment by faerietree** [comment]
Just to be sure, we are talking about the `fastener factory`'s scale setting here?

> I have to set it to 0.1 to get parts that are sized properly, while Mesh -> Add -> Bolt requires a scale setting of 1.0.

The original `bolt factory` (the one that still ships with blender) has not taken several scale related settings into account and also mis-sized the bolts. The 0.1 may be due to bolt factory not having taken into account e.g. `scene scale length` setting.

I must investigate this issue, though I never thought of resizing existing bolts created by the even more buggy bolt factory than this ext is. ;) (just check the commits and closed issues and you'll see what I am talking about, e.g. that the bolt dimensions have been off by several units constantly which rendered all bolts useless for evaluation of mechanical conflict with other parts - or 3D printing; not saying that this ext is better, just that some severe issues were fixed.)

That's why `bolt factory` and `fastener factory` are not compatible, but fastener factory should be able to size any object properly - no matter what created it!

**Comment by faerietree** [comment]
I tested and it works for me. There is the need to select the preset under Properties->Object->Very bottom again, though. This is to reload the proper values from the preset and to trigger a full update.
Else the size is off until such update occurs. Fixing this update issue would be nice.

**Comment by faerietree** [comment]
> When editing an existing bolt from the old builtin bolt library, of course all settings are invalid

Whenever the extension is tasked to operate on an existing object, its mesh is completely recreated from scratch.
No settings are invalid in your case though as bolt factory does not store settings at all. Thus they can not be invalid. `FastenerSettings` are only invalid until a preset is selected or a full update is triggered manually. Can you clarify?

* select an object of type 'MESH'
* select a preset, e.g. M6 under scene properties panel (as described in previous comment).

**Comment by VanessaE** [comment]
Indeed, the existing bolt got replaced, and the settings were valid once I selected a preset.

Scale is consistent now, but is still generally wrong.

My default/startup file has a 10mm cube, scale in the Properties area set to 1.0.

If I add an M6 bolt from the presets (whether by adding a new bolt or by selecting the cube and changing it to an M6 bolt), and set the Fastener Settings' scale to 1.0, I get a ginormous bolt, 10x larger than actual size.

The Fastener Settings' scale value should be multiplied with the overall Blender scale in the Properties area - if a cube spawned while Blender's Properties scale is set to 1.0 would be life-sized (were I to export to STL at scale 1.0 there, and print it), then setting the Fastener scale to 1.0 should produce a life-sized bolt as well.  That is to say, a bolt set to 10mm long in the Fastener settings should result in threads identical in length to a side of that default cube, if all scales are set to 1.0.

**Comment by faerietree** [comment]
Thank you for your answer.

This depends on the definition of the "fastener unit scale". Maybe it should be renamed to `1mm to blender unit mapping`.

* 1.0 means that 1 mm := 1 bu (big size, this is what @worlddevelopment uses as some external tools expect 1 blender unit to correspond to 1 mm, e.g. GCode/CAM tools like Mach3 which we used before the times of [vilemnovak/BlenderCAM](/vilemnovak/BlenderCAM))
* .001 means that 1mm := .001 bu.

**Comment by VanessaE** [comment]
Honestly, I wouldn't do that, "scale" is much easier to understand than "unit mapping".

**Comment by faerietree** [comment]
As a compromise it could be multiplied by 1000.
i.e. then fastener scale setting of
* 1000 => 1 m := 1000 bu <=> .001 m = 1 bu <=> 1 mm = 1 bu (big size, this is what @worlddevelopment uses as their engineering standard, requires adaption of view clip|cut)
* 1.0 => 1 m := 1 bu <=> .001 m = .001 bu <=> 1 mm = .001 bu

Pro this solution is that
* 1 m is SI unit instead of 1 mm

Therefore mapping 1m instead of 1mm makes sense and then you have the 1.0 for the behaviour you expect.
Concerns anyone?
